version: '3'
services:
  build:
    command: 'compile.sh'
    image: 'vimwiki-jekyll/jekyll:v1'
    volumes:
      - '$PWD/../src:/srv/jekyll'
      - '$PWD/../dist:/srv/dist'
      - '$HOME/documents/wiki/wiki:/srv/wiki'
      - '$HOME/documents/wiki/tmpl:/srv/tmpl'
