version: '3'
services:
  test:
    build: .
    volumes:
      - '$HOME/documents/wiki-jekyll/src:/srv/jekyll'
      - '$HOME/documents/wiki-jekyll/dist:/srv/dist'
      - '$HOME/documents/wiki/wiki:/srv/wiki'
      - '$HOME/documents/wiki/tmpl:/srv/tmpl'
    stdin_open: true
    tty: true

